export const SITE = {
  name: 'United Global Consulting',
  shortName: 'UGC',
  tagline_ru: 'Учёба за рубежом без посредников и ложных обещаний',
  tagline_en: 'Study abroad without middlemen or false promises',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://unitedglobalconsulting.uz',
  phone: '+998 99 212 32 24',
  phoneTel: '+998992123224',
  phone2: '+998 88 526 30 00',
  phone2Tel: '+998885263000',
  email: 'unitedglobalconsultinguz@gmail.com',
  address: 'Tashkent, Uzbekistan',
  hours: 'Mon–Sat, 9:00–20:00',
  social: {
    whatsapp: 'https://wa.me/998885263000',
    telegram: 'https://t.me/United_global_consulting',
    instagram: 'https://www.instagram.com/hayotbek_consulting',
  },
  founded: 2026,
} as const;

export const COUNTRY_OPTIONS = [
  'usa',
  'malaysia',
  'singapore',
  'turkey',
  'finland',
  'italy',
  'germany',
  'luxembourg',
  'latvia',
  'poland',
  'romania',
  'hungary',
  'uk',
] as const;
